# Generated by Django 5.0.1 on 2024-01-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Адресс доставки')),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=30, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=30, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название товара')),
                ('image', models.ImageField(upload_to='static/main/img', verbose_name='Изображение товара')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость товара')),
                ('quantity', models.IntegerField(verbose_name='Количество товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField(verbose_name='Id товара')),
                ('orderId', models.IntegerField(verbose_name='Id заказа')),
                ('quantity', models.IntegerField(verbose_name='Количество товара')),
            ],
            options={
                'verbose_name': 'Содержание заказа',
                'verbose_name_plural': 'Содержания заказа',
            },
        ),
    ]
